dist: focal
language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  include:
    - rust: nightly
      env: RUSTFLAGS="-Zsanitizer=address" RUSTDOCFLAGS="-Zsanitizer=address"
      script:
        - rustup component add rust-src
        - cargo build --verbose -Zbuild-std --target x86_64-unknown-linux-gnu
        - cargo test --verbose -Zbuild-std --target x86_64-unknown-linux-gnu
    - rust: nightly
      env: RUSTFLAGS="-Zsanitizer=leak" RUSTDOCFLAGS="-Zsanitizer=leak"
      script:
        - rustup component add rust-src
        - cargo build --verbose -Zbuild-std --target x86_64-unknown-linux-gnu
        - cargo test --verbose -Zbuild-std --target x86_64-unknown-linux-gnu
    - rust: nightly
      env: RUSTFLAGS="-Zsanitizer=memory" RUSTDOCFLAGS="-Zsanitizer=memory"
      script:
        - rustup component add rust-src
        - cargo build --verbose -Zbuild-std --target x86_64-unknown-linux-gnu
        - cargo test --verbose -Zbuild-std --target x86_64-unknown-linux-gnu
    - rust: nightly
      env: RUSTFLAGS="-Zsanitizer=thread" RUSTDOCFLAGS="-Zsanitizer=thread"
      script:
        - rustup component add rust-src
        - cargo build --verbose -Zbuild-std --target x86_64-unknown-linux-gnu
        - cargo test --verbose -Zbuild-std --target x86_64-unknown-linux-gnu
    - rust: nightly
      script:
        - |
          MIRI_NIGHTLY=nightly-$(curl -s https://rust-lang.github.io/rustup-components-history/x86_64-unknown-linux-gnu/miri)
          echo "Installing latest nightly with Miri: $MIRI_NIGHTLY"
          rustup set profile minimal
          rustup default "$MIRI_NIGHTLY"
        - rustup component add miri
        - cargo miri setup
        - cargo miri test --verbose
